src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage.views import homepage_view
from adminPanel.views import adminPanel_view,statistics_view,adminPanel_stats_prodAnalys_view,adminpanel_logout_view,adminPanel_stock_view,adminPanel_addProduct_view\
,adminPanel_editProduct_view,adminPanel_confEditProduct_view,adminPanel_prix_view,adminPanel_pricesEdit_view\
,adminPanel_categories_view,adminPanel_editSold_view,adminPanel_addSold_view,adminPanel_addCategory_view,adminPanel_stats_view
from caisse.views import caisse_view,saleDetails_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view, name= 'home'),
    path('admin-panel', adminPanel_view, name='admin-panel'),
    path('', include('django.contrib.auth.urls')),
    path('admin-panel/statistics', adminPanel_stats_view, name='statistics'),
    path('admin-panel/statistics/view-prod', adminPanel_stats_prodAnalys_view, name='statsViewprod'),
    path('admin-panel/logout', adminpanel_logout_view, name='logout'),
    path('admin-panel/stock', adminPanel_stock_view, name='stock'),
    path('admin-panel/stock/add-product', adminPanel_addProduct_view, name='add-product'),
    path('admin-panel/stock/add-categorie', adminPanel_addCategory_view, name='add-categorie'),
    path('admin-panel/stock/edit-product', adminPanel_editProduct_view, name='edit-product'),
    path('admin-panel/stock/edit-product/confirm', adminPanel_confEditProduct_view, name='conf-edit-product'),
    path('admin-panel/prix', adminPanel_prix_view, name='prix'),
    path('admin-panel/prix/prix-categories', adminPanel_categories_view, name='prix-categorie'),
    path('admin-panel/prix/prices-edit', adminPanel_pricesEdit_view, name='price-edit'),
    path('admin-panel/prix/add-sold', adminPanel_addSold_view, name='add-sold'),
    path('admin-panel/prix/edit-sold', adminPanel_editSold_view, name='edit-sold'),
    path('admin-panel/prix/delete-sold', adminPanel_editSold_view, name='delete-sold'),
    #CAISSE URLS 
    path('caisse', caisse_view, name='caisse'),
    path('sale-details', saleDetails_view, name='sale-details'),
        


]

src/adminPanel/models.py
from unicodedata import name
from django.db import models
from datetime import datetime


# Create your models here.
class soldModel(models.Model):
	sold_productid			= models.IntegerField(verbose_name='produit id', unique=True)
	sold_productname		= models.CharField(verbose_name='nom produit', max_length=50, null=False)
	sold_starting_date		= models.DateField(verbose_name='date debut Sold')
	sold_ending_date		= models.DateField(verbose_name='date fin Sold')
	sold_price				= models.IntegerField(verbose_name='prix Sold', default=0)
	sold_soldProducts		= models.IntegerField(verbose_name='quantité des produits vendu on Sold',default=0)
	sold_active				= models.BooleanField(verbose_name='sold actif', default=False)
	def __str__(self):
		return self.sold_productname

	class Meta:
		ordering = ['sold_starting_date']
		verbose_name = 'sold'
		verbose_name_plural = 'solded products'



class productsModel(models.Model):
	#product_id = models.AutoField(verbose_name='id',primary_key=True)
	productname 		= models.CharField(verbose_name='nom produit', max_length=50, null=False, unique= True)
	quantity			= models.IntegerField(verbose_name='quantité', null=True)
	date_delivered		= models.DateField(verbose_name='date arrivé', auto_now_add= True)
	date_ex				= models.DateField(verbose_name='date primé')
	suplier				= models.CharField(verbose_name='livrer par', max_length=50)
	category			= models.CharField(verbose_name='categorie', max_length=50, default='autre')
	price				= models.IntegerField(verbose_name='prix',null=False, default='0')
	sold				= models.BooleanField(verbose_name='solder', default=False)
	purchasePrx			= models.IntegerField(null=False,default=-1)
	unityPerBox			= models.IntegerField(null = False,default=10)
	unitsSold_thisMonth = models.CharField(verbose_name='uniter vendue ce mois',max_length=20,null=False)

	def __str__(self):
		return self.productname

	class Meta:
		ordering = ['date_delivered']
		verbose_name = 'stock'
		verbose_name_plural = 'products'


	def monthlyReset(currMonth):
		prods = productsModel.objects.all()
		for prod in prods:
			prod.unitsSold_thisMonth = "0."+str(currMonth)


class categoryModel(models.Model):
	categoryname = models.CharField(verbose_name='nom category', max_length=50, null=False,unique=True)
	#length = models.IntegerField(verbose_name='nombre des produits dans la categorie', default=0)


	def __str__(self):
		return self.categoryname

""" 	class Meta:
		ordering = ['length']
		verbose_name = 'categorie'
		verbose_name_plural = 'les categories' """


class SchedualedSpends(models.Model):
	name		= models.CharField(verbose_name='nom de la depence programmer',max_length=50, null=False)
	amount 		= models.IntegerField(verbose_name='montant de la depence',null=False)
	dateDelv 	= models.DateField(verbose_name='date programmer pour la depence')
	
	def	__str__(self):
		return self.name
	

src/adminPanel/forms.py
from django import forms

from adminPanel.models import productsModel

class createProductFrom(forms.ModelForm):

	class Meta:
		model= productsModel
		fields= ['productname', 'quantity', 'date_ex', 'category', 'price','suplier', ]

	

src/adminPanel/views.py
from django.shortcuts import render,redirect
from adminPanel.models import productsModel, soldModel, categoryModel,SchedualedSpends
from caisse.models import saleModel
from adminPanel.forms import createProductFrom
from django.db.models import Q
import urllib.request
from datetime import datetime
counter = 1
prods = productsModel.objects.all()

currMonth = int(datetime.today().month)
if currMonth > int(prods.get(id=1).unitsSold_thisMonth.split('.')[1]):
	productsModel.monthlyReset(currMonth)

# Create your views here.
def adminPanel_view(request):
	context = {}
	context['username'] = request.user.username
	return render(request, 'adminPanel/admin-panel.html',context)

def statistics_view(request):
	return render(request, 'adminPanel/statistics.html',{})

def adminpanel_logout_view(request):
	logout(request)
	return redirect('home')

def adminPanel_stock_view(request):
	context = {}
	global counter
	products = productsModel.objects.all()
	context['products'] = products	
	solds = soldModel.objects.all()
	context['solds'] = solds	
	if 'search' in request.POST:		
		search_rqst = request.POST['searchprd']
		context['search_title'] = search_rqst
		context['products']= products.filter(Q(suplier__contains=search_rqst) | Q(productname__contains =search_rqst)\
			|Q(date_ex__contains=search_rqst) | Q(date_delivered__contains=search_rqst) | Q(price__contains=search_rqst)\
			|Q(category__contains=search_rqst))	
		
	if 'orderby-id' in request.POST:
		print(counter)
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-id')
		else:
			context['products']= products.order_by('id')	
	
	elif 'orderby-datedelv' in request.POST:
		print(counter)
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-date_delivered')
		else:
			context['products']= products.order_by('date_delivered')

	elif 'orderby-quantity' in request.POST:
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-quantity')
		else:
			context['products']= products.order_by('quantity')	
	
	elif 'orderby-price' in request.POST:
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-price')
		else:
			context['products']= products.order_by('price')	

	elif 'orderby-date-ex' in request.POST:
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-date_ex')
		else:
			context['products']= products.order_by('date_ex')	
	elif 'orderby-sold' in request.POST:
		counter*=-1
		if counter == -1:
			context['products']= products.order_by('-sold')
		else:
			context['products']= products.order_by('sold')

	
	return	render(request, 'adminPanel/stock.html',context)


def adminPanel_addProduct_view(request):
	context = {}
	if 	request.POST:
		form = createProductFrom(request.POST)
		if form.is_valid():
			form.save()
			form = createProductFrom()
			return redirect('stock')
		else:
			print("its not valid")
			context['form'] = form	

	
	return render(request, 'adminPanel/add-product.html', context)

def adminPanel_addCategory_view(request):
	context = {}
	if request.POST:
		newcategory = categoryModel(Categoryname = request.POST['categoryname'])
		newcategory.save()
		return redirect('stock')
	return render(request, 'adminPanel/add-categorie.html')


def adminPanel_editProduct_view(request):
	context = {}
	if 'edit' in request.POST:
		productid = request.POST['edit']
		products = productsModel.objects.all()
		oldform = products.get(id = productid)
		context['oldform'] = oldform

	

	return render(request, 'adminPanel/edit-product.html', context)	


def adminPanel_confEditProduct_view(request):
	context = {}
	if request.POST:
		print("\n conf view working \n")
		form = request.POST
		oldformid = form['oldformid']
		products = productsModel.objects.all()
		oldform = products.get(id = oldformid)

		#treating the sold value(-1 and 1) 
		if form['sold']=="Arrête Sold":
			sold=True
		else:
			sold=False
		#treating the price value(DA)
		price = form['price']
		price = price.replace('DA','')

		oldform.productname=form['productname']
		oldform.quantity=form['quantity']
		oldform.date_ex=form['date_ex']
		oldform.suplier=form['suplier']
		oldform.category=form['category']
		oldform.price=price
		oldform.sold=sold
		oldform.save()

		return redirect('stock')
	else:
		print("\nits not working\n")

	return render(request, 'adminPanel/conf-edit.html', context)	

def adminPanel_prix_view(request):
	context = {}
	products = productsModel.objects.all()
	context['products'] = products

	solds = soldModel.objects.all()
	context['solds'] = solds
	if 'search' in request.POST:		
		search_rqst = request.POST['searchprd']
		context['search_title'] = search_rqst
		context['products']= products.filter(Q(suplier__contains=search_rqst) | Q(productname__contains =search_rqst)\
			|Q(date_ex__contains=search_rqst) | Q(date_delivered__contains=search_rqst) | Q(price__contains=search_rqst)\
			|Q(category__contains=search_rqst))			 

	return render(request, 'adminPanel/prix.html', context)

def adminPanel_pricesEdit_view(request):
	context = {}
	products = productsModel.objects.all()
	context['products'] = products	

	if 'price-edit' in request.POST:
		productid = request.POST['price-edit']
		oldform = products.get(id = productid)
		context['oldform'] = oldform	
		context['return'] = 'prices'

	if 'confirm-edit' in request.POST:
		print("\nconf\n")
		newform = request.POST
		oldform = products.get(id = newform['oldformid'])

		if 'price' in newform:
			oldform.price = newform['price']
		if 'sold-price' in newform:
			oldform.sold_price = newform['sold-price']

		oldform.save()
		context['return'] = 'stats'
			
		return redirect('prix')
	if 'statsEditPrx' in request.POST:
		productid = request.POST['statsEditPrx']
		oldform = products.get(id=productid)
		context['oldform'] = oldform	
		context['return'] = 'stats'

	return render(request, 'adminPanel/prices-edit.html', context)	


def adminPanel_categories_view(request):
	context = {}
	products = productsModel.objects.all()

	if 'cat-boissants' in request.POST:
		context['products']= products.filter(Q(category__contains='boissants'))
		context['category'] = 'Boissnats'
	if 'cat-nouriture' in request.POST:
		context['products'] = products.filter(Q(category__contains='nouriture'))
		context['category'] = 'Nouriture'
	if 'cat-produits' in request.POST:
		context['products'] = products.filter(Q(category__contains='produits'))
		context['category'] = 'Produits'
	if 'cat-autre' in request.POST:
		context['products'] = products.filter(Q(category__contains='autre'))
		context['category'] = 'Autre'

	return render(request , 'adminPanel/prix-categories.html', context)

def adminPanel_addSold_view(request):
	context = {}
	products = productsModel.objects.all()
	if 'solding-product-id' in request.POST:
		productid = request.POST['solding-product-id']
		product = products.get(id=productid)
		context['product'] = product

	if	'add-sold' in request.POST:
		form = request.POST
		productid = form['product-id']
		product = products.get(id=productid)
		
		soldingform = soldModel(sold_productid= product.id, sold_productname= product.productname,\
		sold_starting_date= form['start-sold'], sold_ending_date = form['end-sold'], sold_price = form['sold-price'])

		soldingform.save()
		product.sold = True
		product.save()
		return redirect('prix')
	return render(request, 'adminPanel/add-sold.html', context)

def adminPanel_editSold_view(request):
	context = {}
	products = productsModel.objects.all()
	soldDB = soldModel.objects.all()
	context['todayDate']= datetime.date.today()

	if 'solding-product-id' in request.POST:
		productid = request.POST['solding-product-id']
		product = products.get(id = productid)
		context['product'] = product
		if product.sold:
			sold = soldDB.get(sold_productid=productid)
			context['product_sold'] = sold
		
			if sold.sold_starting_date <= datetime.date.today():
				context['sold_active'] = True
			else: context['sold_active'] = False  
	
	if	'add-sold' in request.POST:
		form = request.POST
		productid = form['product-id']
		product = products.get(id = productid)
		
		soldingform = soldModel(sold_productid= product.id, sold_productname= product.productname,\
		sold_starting_date= form['start-sold'], sold_ending_date = form['end-sold'], sold_price = form['sold-price'])

		soldingform.save()
		product.sold = True
		product.save()
		return redirect('prix')

	if 'edit-sold' in request.POST:	
		form = request.POST
		soldingform = soldDB.get(sold_productid = form['product-id'])
		soldingform.sold_price = form['sold-price']
		soldingform.sold_starting_date = form['start-sold']
		soldingform.sold_ending_date = form['end-sold']
		soldingform.save()
		return redirect('prix')
	
	if 'delete-sold' in request.POST:
		form = request.POST
		sold = soldDB.get(sold_productid=form['product-id'])
		sold.delete()
		product = products.get(id= form['product-id'])
		product.sold = False
		product.save()

		return redirect('prix')
	return render(request, 'adminPanel/edit-sold.html', context)

def adminPanel_stats_view(request):
	context = {}
	products = productsModel.objects.all()
	sales = saleModel.objects.all()
	spends = SchedualedSpends.objects.all()
	now = datetime.today()
	#add a str date
	monthStart = datetime(now.year,now.month,1).date()
	currMonthSales = saleModel.objects.filter(saleDate__gte=monthStart,saleDate__lte=now)
	context['producst'] = products
	context['currMonthSales'] = currMonthSales

	Rev = 0
	for sale in sales:
		for saleProd in sale.saleProducts.all():
			Rev+= saleProd.price
	context['monthRev']= Rev
	yesterday = datetime(now.year,now.month,now.day-1).date()
	todaySales = saleModel.objects.filter(saleDate__gt=yesterday)
	context['todaySales'] = todaySales
	Rev = 0
	for sale in todaySales:
		for saleProd in sale.saleProducts.all():
			Rev += saleProd.price
	context['todayRev'] = Rev

	mostSold = products.order_by('-unitsSold_thisMonth')[:5]
	context['thisMonth_mostSoldPrds'] = mostSold

src/adminPanel/templates/adminPanel/add-product.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ajouter produit</title>
    
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.min.css'%}">
    <script type="text/javascript" src="{% static 'adminPanel/js/bootstrap.min.js' %}"></script>
    <!-- font awesome -->
    
    <!--<script src="https://use.fontawesome.com/46a40ea73b.js"></script> -->
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/fontawesome.css' %}">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
body{
    background-color: #27DB39;
}

.registration-form{
	padding: 50px 0;
}

.registration-form form{
    background-color: #fff;
    max-width: 600px;
    margin: auto;
    padding: 50px 70px;
    border-top-left-radius: 30px;
    border-top-right-radius: 30px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.075);
}



.registration-form .item{
	border-radius: 20px;
    margin-bottom: 25px;
    padding: 10px 20px;
}
.header{
	color: black;
	font-weight: bold;
	text-align: center;
	margin-bottom: 20px;
}

.backicon i{
    color: white;
    font-size: 1.2rem;
    margin-left: 50px;
}


</style>
<body>
    <div class="registration-form">
        <div>
              <a  href="/admin-panel/stock" class="backicon"><i class="fas fa-arrow-left"> Retour</i> </a>
        </div>
        <form method="post">
			{% csrf_token %}

        	<div class="header"><h3>Nouveau Produit</h3></div>
            
            <div class="form-group">
                <input type="text" name="productname" maxlength="50" required="" id="id_productname" placeholder="nom produit" class="form-control item">
            </div>
            <div class="form-group">
                <input type="number" name="quantity" required="" id="id_quantity" placeholder="quantite" class="form-control item">
            </div>
            <div class="form-group">
                <input type="text" name="date_ex" required="" id="id_date_ex" placeholder="date EX" onfocus="(this.type='date')" class="form-control item">
            </div>
            <div class="form-group">
                <input type="text" name="category" maxlength="50" required="" id="id_suplier" placeholder="categorie" class="form-control item">
            </div>
            <div class="form-group">
                <input type="number" name="price" maxlength="50" required="" id="id_suplier" placeholder="prix" class="form-control item">
            </div>
            <div class="form-group">
                <input type="text" name="suplier" maxlength="50" required="" id="id_suplier" placeholder="livrer par" class="form-control item">
            </div>
            

            {% for field in form %}

                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endfor %}
            
            <div class="text-center">
                <button type="submit" class="btn btn-success">Ajouter Produit</button>
            </div> 
        </form>
        
    </div>

</body>
</html>

src/adminPanel/templates/adminPanel/add-sold.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Solder</title>
    
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.min.css'%}">
    <script type="text/javascript" src="{% static 'adminPanel/js/bootstrap.min.js' %}"></script>
    <!-- font awesome -->
    
    <!--<script src="https://use.fontawesome.com/46a40ea73b.js"></script> -->
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/fontawesome.css' %}">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
body{
    background-color: #27DB39;
}

.registration-form{
    padding: 50px 0;
}

.registration-form form{
    background-color: #fff;
    max-width: 600px;
    margin: auto;
    padding: 50px 70px;
    border-top-left-radius: 30px;
    border-top-right-radius: 30px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.075);
}



.registration-form .item{
    border-radius: 20px;
    margin-bottom: 25px;
    padding: 10px 20px;
}
.header{
    color: black;
    font-weight: bold;
    text-align: center;
    margin-bottom: 2px;
}

.sub-header{
    color: black;
    font-weight: bold;
    text-align: center;
    margin-bottom: 50px;

}
.backicon i{
    color: white;
    font-size: 1.2rem;
    margin-left: 50px;
}



</style>
<body>
    <div class="registration-form">
        <div>
              <a  href="/admin-panel/prix" class="backicon"><i class="fas fa-arrow-left"> Retour</i> </a>
        </div>
        <form method="post">
            {% csrf_token %}

            <div class="header"><h3>Solder Produit:</h3></div>
            <div class="sub-header"><h6>({{product.productname}},prix:{{product.price}}DA)</h6></div>
            
            <div class="form-group">
                <input type="text" name="sold-price" maxlength="50" id="id_suplier" placeholder="Prix de Sold" class="form-control item" onfocus="(this.type='number')">
            </div>
            
            <div class="form-group">
                <input type="text" name="start-sold" required="" id="id_quantity" placeholder="Date debut de Sold" class="form-control item" onfocus="(this.type='date')" min="{{todaDate}}">
            </div>

            <div class="form-group">
                <input type="text" name="end-sold" required="" id="id_quantity" placeholder="Date fin de Sold" class="form-control item" onfocus="(this.type='date')" min="{{todayDate}}">
            </div>
           
           
                <input type="number" name="product-id" value="{{product.id}}" hidden="" id="id_suplier">
            

            {% for field in form %}

                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endfor %}
            
            <div class="text-center">
                <button type="submit" name="add-sold" class="btn btn-success">Confirmer Sold</button>
            </div> 
        </form>
        
    </div>

</body>
</html>

src/adminPanel/templates/adminPanel/admin-panel.html
{% extends 'adminPanel/adminbase.html' %}

{% block style %}
		
		.container{
			display: grid;
			width: 100%;
			justify-content: center;
			margin-top: 100px;
			text-decoration: none;
		}
		.divs{
			justify-content: center;			
			text-decoration: none;
			display: block;
			width: 80vw;
			height: 80px;
			background-color: #ffa500;
			margin-bottom: 10px;
			text-align: center;
			color: black;
			padding:0;
		}
		.divs h3{
			padding: 23px 0 0 0;
			margin:0;
			font-weight:bold;
		}
		.container a:hover {
			color: white;
		    text-decoration: none;
		    background-color: black;
		    transition: 0.5s;
		}
		.fas{
			font-size:1.7rem;
		}

		
{% endblock %}

{% block title %}
	Admin Panel	
{% endblock %}

{% block content%}
	<div class="container">
		<div class="headers">
			<a href="admin-panel/stock" class="divs" >
				<div>
					<h3>Stock <i class="fas fa-clipboard-list"></i></h3>
				</div>
			</a>			
		</div>
		<div class="headers">
			<a href="admin-panel/prix" class="divs">
				<div>
					<h3>Prix <i class="fas fa-search-dollar"></i></h3>
				</div>
			</a>
		</div>
		<div class="headers">
			<a href="admin-panel/statistics" class="divs">
				<div>
					<h3>Statistics <i class="fas fa-chart-line"></i></h3>
				</div>
			</a>
		</div>
	</div>
{% endblock %}	

src/adminPanel/templates/adminPanel/edit-product.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Editer Produit</title>
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'adminPanel/css/bootstrap.min.css'%}">
    <script type="text/javascript" src="{% static 'adminPanel/js/bootstrap.min.js' %}"></script>
    <!-- font awesome -->
    
    <!--<script src="https://use.fontawesome.com/46a40ea73b.js"></script> -->
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'adminPanel/fontawsm/css/fontawesome.css' %}">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
body{
    background-color: #A1DB27;
}

.registration-form{
	padding: 50px 0;
}

.registration-form form{
    background-color: #fff;
    max-width: 600px;
    margin: auto;
    padding: 50px 70px;
    border-top-left-radius: 30px;
    border-top-right-radius: 30px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.075);
}



.registration-form .item{
	border-radius: 20px;
    margin-bottom: 25px;
    padding: 10px 20px;
}
.header{
	color: black;
	font-weight: bold;
	text-align: center;
	margin-bottom: 20px;
}

.backicon i{
    color: white;
    font-size: 1.2rem;
    margin-left: 50px;
}


</style>
<body>
    <div class="registration-form">
        <div>
              <a  href="/admin-panel/stock" class="backicon"><i class="fas fa-arrow-left"> Retour</i> </a>
        </div>
        <form method="post" action="edit-product/confirm">
			{% csrf_token %}

        	<div class="header"><h3>Editer Produit</h3></div>
            
            <div class="form-group">
                <input type="text" name="productname" maxlength="50" required="" id="id_productname" placeholder="nom produit" class="form-control item" value={{oldform.productname}}>
            </div>
            <div class="form-group">
                <input type="number" name="quantity" required="" id="id_quantity" placeholder="quantite" class="form-control item"
                value= {{oldform.quantity}}>
            </div>
            <div class="form-group">
                <input type="text" name="date_ex" required="" id="id_date_ex" placeholder="date EX" onfocus="(this.type='date')" class="form-control item" value="{{oldform.date_ex|date:'Y-m-d'}}">
            </div>
            <div class="form-group">
                <input type="text" name="price" maxlength="50" required="" id="id_price" placeholder="prix" class="form-control item" value="{{oldform.price}}DA">
            </div>
            <div class="form-group">
                <input type="text" name="category" maxlength="50" required="" id="id_category" placeholder="categorie" class="form-control item" value={{oldform.category}}>
            </div>
            <div class="form-group">
                <input type="text" name="suplier" maxlength="50" required="" id="id_suplier" placeholder="livrer par" class="form-control item" value={{oldform.suplier}}>
            </div>
            {% if oldform.sold %}
                <div class="text-right" style="margin-bottom:20px">
                    <input type="button" name="sold" value="Arrête Sold" onclick='jsfunc()' class="btn btn-danger" id="sold-button">
                </div>
            {% endif %}    
            <input type="text" name="sold" hidden="" id="sold-hidden-input">


            <input type="text" name="oldformid" value={{oldform.id}} hidden="">

            {% for field in form %}

                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endfor %}
            
            <div class="text-center">
                <button type="submit" class="btn btn-success" name="confirm-edit " style="margin-bottom:-10px">Confirmer l'Edit</button>
            </div> 
        </form>
        
    </div>
    <script >
        function jsfunc(){
            inpt = document.getElementById("sold-button")
            if (inpt.value == "Arrête Sold"){
                inpt.value = "Resumer Sold";
                inpt.className = "btn btn-primary";
            }else{
                inpt.value = "Arrête Sold";
                inpt.className = "btn btn-danger";
            }
            soldinpt = document.getElementById("sold-hidden-input");
            soldinpt.value = inpt.value; 
        }
    </script>
</body>
</html>